using System;
using System.Collections.Generic;
using System.Linq;
using PCCC.DAL;
using System.Windows.Forms;
using PCCC.Models.AutoGenerated;

namespace PCCC.Repositories
{
    class DAO_Factor: Repository<Factor>
    {
        public List<Factor> All()
        {
            var listFactor = from a in dataContext.Factors select a;
            return listFactor.ToList();
        }
        public bool ThemHS(int id, string detail, double val, string sign, bool sta)
        {
            try
            {
                Factor fa = new Factor();
                fa.ID = id;
                fa.Detail = detail;
                fa.Value = val;
                fa.SignFactor = sign;
                fa.Statuses = sta;
                dataContext.Factors.InsertOnSubmit(fa);
                dataContext.SubmitChanges();
                return true;
            }
            catch (Exception)
            {
                MessageBox.Show("Dữ liệu không hợp lệ. Xin vui lòng kiểm tra lại!");
                return false;
            }
        }
        public bool SuaHS(int id, string detail, double val, string sign, bool sta)
        {
            try
            {
                Factor fa = dataContext.Factors.Single(x => x.ID == id);
                fa.Detail = detail;
                fa.Value = val;
                fa.SignFactor = sign;
                fa.Statuses = sta;
                dataContext.SubmitChanges();
                return true;
            }
            catch (Exception)
            {
                MessageBox.Show("Dữ liệu không hợp lệ. Xin vui lòng kiểm tra lại!");
                return false;
            }
        }
        public bool XoaHS(int id)
        {
            try
            {
                Factor fa = dataContext.Factors.Single(i => i.ID == id);
                dataContext.Factors.DeleteOnSubmit(fa);
                dataContext.SubmitChanges();
                return true;
            }
            catch (Exception)
            {
                MessageBox.Show("Dữ liệu không hợp lệ. Xin vui lòng kiểm tra lại!");
                return false;
            }
        }
    }
}
