using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Windows.Forms;
using PCCC.DAL;
using PCCC.Models.AutoGenerated;

namespace PCCC.Repositories
{
    public class DAO_City: Repository<City>
    {
        public List<City> All()
        {
            var list = from a in dataContext.Cities select a;
            return list.ToList();
        }
        public bool ThemTP(int id, string name, string codeCity)
        {
            try
            {
                City ci = new City();
                ci.ID = id;
                ci.Name = name;
                ci.CCity = codeCity;
                dataContext.Cities.InsertOnSubmit(ci);
                dataContext.SubmitChanges();
                return true;
            }
            catch(Exception)
            {
                MessageBox.Show("Dữ liệu không hợp lệ. Xin vui lòng kiểm tra lại!");
                return false;
            }
        }
        public bool SuaTP(int id, string name, string ccity)
        {
            try
            {
                City ci = dataContext.Cities.Single(x => x.ID == id);
                ci.Name = name;
                ci.CCity = ccity;
                dataContext.SubmitChanges();
                return true;
            }
            catch (Exception)
            {
                MessageBox.Show("Dữ liệu không hợp lệ. Xin vui lòng kiểm tra lại!");
                return false;
            }
        }
        public bool XoaTP(int id)
        {
            try
            {
                City ci = dataContext.Cities.Single(i => i.ID == id);
                dataContext.Cities.DeleteOnSubmit(ci);
                dataContext.SubmitChanges();
                return true;
            }
            catch (Exception)
            {
                MessageBox.Show("Dữ liệu không hợp lệ. Xin vui lòng kiểm tra lại!");
                return false;
            }
        }
    }
}
