using System;
using System.Collections.Generic;
using System.Linq;
using PCCC.DAL;
using System.Windows.Forms;
using PCCC.Models.AutoGenerated;

namespace PCCC.Repositories
{
    class DAO_LogErr: Repository<LogError>
    {
        public List<LogError> All()
        {
            var listLogError = from a in dataContext.LogErrors select a;
            return listLogError.ToList();
        }
        public bool ThemLoi(int id, string mess, string stack, DateTime create)
        {
            try
            {
                LogError log = new LogError();
                log.ID = id;
                log.Messages = mess;
                log.StackTrace = stack;
                log.CreateDate = create;
                dataContext.LogErrors.InsertOnSubmit(log);
                dataContext.SubmitChanges();
                return true;
            }
            catch (Exception)
            {
                MessageBox.Show("Dữ liệu không hợp lệ. Xin vui lòng kiểm tra lại!");
                return false;
            }
        }
        public bool SuaLoi(int id, string mess, string stack, DateTime create)
        {
            try
            {
                LogError log = dataContext.LogErrors.Single(x => x.ID == id);
                log.Messages = mess;
                log.StackTrace = stack;
                log.CreateDate = create;
                dataContext.SubmitChanges();
                return true;
            }
            catch (Exception)
            {
                MessageBox.Show("Dữ liệu không hợp lệ. Xin vui lòng kiểm tra lại!");
                return false;
            }
        }
        public bool XoaLoi(int id)
        {
            try
            {
                LogError log = dataContext.LogErrors.Single(i => i.ID == id);
                dataContext.LogErrors.DeleteOnSubmit(log);
                dataContext.SubmitChanges();
                return true;
            }
            catch (Exception)
            {
                MessageBox.Show("Dữ liệu không hợp lệ. Xin vui lòng kiểm tra lại!");
                return false;
            }
        }
    }
}
