using System;
using System.Collections.Generic;
using System.Linq;
using PCCC.DAL;
using System.Windows.Forms;
using PCCC.Models.AutoGenerated;
namespace PCCC.Repositories
{
    class DAO_Probability: Repository<Probability>
    {
        public List<Probability> All()
        {
            var listPro = from a in dataContext.Probabilities select a;
            return listPro.ToList();
        }
        public bool ThemGTChoPhep(int id, double numAllow)
        {
            try
            {
                Probability pro = new Probability();
                pro.ID = id;
                pro.ProAllow = numAllow;
                //cai nay e chua chinh xong hihi
                dataContext.Districts.InsertOnSubmit(di);
                dataContext.SubmitChanges();
                return true;
            }
            catch (Exception)
            {
                MessageBox.Show("Dữ liệu không hợp lệ. Xin vui lòng kiểm tra lại!");
                return false;
            }
        }
        public bool SuaTinh(int id, string name, double destiny, int idCity)
        {
            try
            {
                District di = dataContext.Districts.Single(x => x.ID == id);
                di.Name = name;
                di.Destiny = destiny;
                di.IDCity = idCity;
                dataContext.SubmitChanges();
                return true;
            }
            catch (Exception)
            {
                MessageBox.Show("Dữ liệu không hợp lệ. Xin vui lòng kiểm tra lại!");
                return false;
            }
        }
        public bool XoaTinh(int id)
        {
            try
            {
                District di = dataContext.Districts.Single(i => i.ID == id);
                dataContext.Districts.DeleteOnSubmit(di);
                dataContext.SubmitChanges();
                return true;
            }
            catch (Exception)
            {
                MessageBox.Show("Dữ liệu không hợp lệ. Xin vui lòng kiểm tra lại!");
                return false;
            }
        }
    }
}
