using System;
using System.Collections.Generic;
using System.Linq;
using PCCC.DAL;
using System.Windows.Forms;
using PCCC.Models.AutoGenerated;

namespace PCCC.Repositories
{
    class DAO_Formula: Repository<Formula>
    {
        public List<Formula> All()
        {
            var listFormula = from a in dataContext.Formulas select a;
            return listFormula.ToList();
        }
        public bool ThemKQ(int id, string sFor, int idCon, string detail, int idFac)
        {
            try
            {
                Formula fo = new Formula();
                fo.ID = id;
                fo.SFormula = sFor;
                fo.IDCon = idCon;
                fo.Detail = detail;
                fo.IDFac = idFac;
                dataContext.Formulas.InsertOnSubmit(fo);
                dataContext.SubmitChanges();
                return true;
            }
            catch (Exception)
            {
                MessageBox.Show("Dữ liệu không hợp lệ. Xin vui lòng kiểm tra lại!");
                return false;
            }
        }
        public bool SuaKQ(int id, string sFor, int idCon, string detail, int idFac)
        {
            try
            {
                Formula fo = dataContext.Formulas.Single(x => x.ID == id);
                fo.SFormula = sFor;
                fo.IDCon = idCon;
                fo.Detail = detail;
                fo.IDFac = idFac;
                dataContext.SubmitChanges();
                return true;
            }
            catch (Exception)
            {
                MessageBox.Show("Dữ liệu không hợp lệ. Xin vui lòng kiểm tra lại!");
                return false;
            }
        }
        public bool XoaKQ(int id)
        {
            try
            {
                Formula fo = dataContext.Formulas.Single(i => i.ID == id);
                dataContext.Formulas.DeleteOnSubmit(fo);
                dataContext.SubmitChanges();
                return true;
            }
            catch (Exception)
            {
                MessageBox.Show("Dữ liệu không hợp lệ. Xin vui lòng kiểm tra lại!");
                return false;
            }
        }
    }
}
