using System;
using System.Collections.Generic;
using System.Linq;
using PCCC.DAL;
using System.Windows.Forms;
using PCCC.Models.AutoGenerated;
namespace PCCC.Repositories
{
    class DAO_District: Repository<District>
    {
        public List<District> All()
        {
            var listDistrict = from a in dataContext.Districts select a;
            return listDistrict.ToList();
        }
        public bool ThemTinh(int id, string name, double destiny, int idCity)
        {
            try
            {
                District di = new District();
                di.ID = id;
                di.Name = name;
                di.Destiny = destiny;
                di.IDCity = idCity;
                dataContext.Districts.InsertOnSubmit(di);
                dataContext.SubmitChanges();
                return true;
            }
            catch(Exception)
            {
                MessageBox.Show("Dữ liệu không hợp lệ. Xin vui lòng kiểm tra lại!");
                return false;
            }
        }
        public bool SuaTinh(int id, string name, double destiny, int idCity)
        {
            try
            {
                District di = dataContext.Districts.Single(x => x.ID == id);
                di.Name = name;
                di.Destiny = destiny;
                di.IDCity = idCity;
                dataContext.SubmitChanges();
                return true;
            }
            catch (Exception)
            {
                MessageBox.Show("Dữ liệu không hợp lệ. Xin vui lòng kiểm tra lại!");
                return false;
            }
        }
        public bool XoaTinh(int id)
        {
            try
            {
                District di = dataContext.Districts.Single(i => i.ID == id);
                dataContext.Districts.DeleteOnSubmit(di);
                dataContext.SubmitChanges();
                return true;
            }
            catch (Exception)
            {
                MessageBox.Show("Dữ liệu không hợp lệ. Xin vui lòng kiểm tra lại!");
                return false;
            }
        }
    }
}
