//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCCC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetailFactor
    {
        public int ID { get; set; }
        public int IDFactor { get; set; }
        public double Value { get; set; }
        public string SignFactor { get; set; }
        public string Detail { get; set; }
        public bool Statuses { get; set; }
    }
}
