//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCCC.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PCCCEntities : DbContext
    {
        public PCCCEntities()
            : base("name=PCCCEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<City> Cities { get; set; }
        public virtual DbSet<Contruction> Contructions { get; set; }
        public virtual DbSet<DetailFactor> DetailFactors { get; set; }
        public virtual DbSet<District> Districts { get; set; }
        public virtual DbSet<Facility> Facilities { get; set; }
        public virtual DbSet<Factor> Factors { get; set; }
        public virtual DbSet<Formula> Formulae { get; set; }
        public virtual DbSet<LogError> LogErrors { get; set; }
        public virtual DbSet<Picture> Pictures { get; set; }
        public virtual DbSet<Probability> Probabilities { get; set; }
    }
}
